# Use the Node.js base image for the development environment
FROM node:18-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY ./web/package.json ./web/yarn.lock .

# Copy .env-cmdrc file
COPY ./.env-cmdrc .
COPY ./web/.env-cmdrc .

# Install dependencies
RUN apk add python3 make g++ && rm -rf /var/cache/apk/* \
  && npm install -g corepack \
  && corepack enable \
  && corepack prepare yarn@4.6.0 --activate

# Copy the rest of the application code
COPY ./web .

# Install development dependencies
RUN CI=false yarn install --immutable

# Set environment variables
ARG PORT
ENV PORT $PORT

ARG REACT_APP_BACKEND=http://localhost:9000
ENV REACT_APP_BACKEND $REACT_APP_BACKEND

ARG REACT_APP_STAT_URL=http://localhost:9100
ENV REACT_APP_STAT_URL $REACT_APP_STAT_URL

ARG REACT_APP_COUNTRY_NAME=Seychelles
ENV REACT_APP_COUNTRY_NAME $REACT_APP_COUNTRY_NAME

# Other environment variables
ARG REACT_APP_COUNTRY_FLAG_URL
ENV REACT_APP_COUNTRY_FLAG_URL $REACT_APP_COUNTRY_FLAG_URL

ARG COUNTRY_CODE
ENV COUNTRY_CODE $COUNTRY_CODE

ARG REACT_APP_MAPBOXGL_ACCESS_TOKEN
ENV REACT_APP_MAPBOXGL_ACCESS_TOKEN $REACT_APP_MAPBOXGL_ACCESS_TOKEN

ARG REACT_APP_MAP_TYPE
ENV REACT_APP_MAP_TYPE $REACT_APP_MAP_TYPE

ARG REACT_APP_ENABLE_REGISTRATION
ENV REACT_APP_ENABLE_REGISTRATION $REACT_APP_ENABLE_REGISTRATION

ARG REACT_APP_GOVERNMENT_MINISTRY
ENV REACT_APP_GOVERNMENT_MINISTRY $REACT_APP_GOVERNMENT_MINISTRY

# Expose the development port
EXPOSE $PORT

# Run the development server using the start:dev script
CMD ["yarn", "start:dev"]
